### ISSUE TITLE
.eslintrc should not be included in dist packages

### ISSUE THREAD

**Issue by eddiemonge** [strongloop/strong-tools#70]
If you open those files in an editor that supports eslint it complains that the eslint extends isn't installed.

This repo is an example. This [extends](https://github.com/strongloop/strong-tools/blob/master/.eslintrc#L2)
complains because [eslint-config-strongloop](https://github.com/strongloop/strong-tools/blob/master/package.json#L46) isn't installed since it is a devDep.

**Comment by sam-github** [comment]
@eddiemonge but why does this matter? its only an editor warning, I assume. its rare to open the js files from an npm install. it happens when trying to debug, but when you open an editor on a package internals, you are going into the guts of a package, you should be prepared for this.

Also, its not clear. Are you reporting that strong-tools itself has a .eslintrc, or that slt-release does not hide the .eslintrc (as it does for the test and .travis.yml) when it releases? Because I'm pretty sure that almost every npm package we publish has a .eslintrc.

And what about when your editor complains that mocha or tap isn't installed, because it needs them to run the unit tests, because your editor has the great feature of showing test coverage inline, as it does eslint? We aren't going to add the test/ back into the pubished package!

This is a rathole down which I'm not sure we want to go.

**Comment by eddiemonge** [comment]
Closing in favor of https://github.com/strongloop/strong-tools/issues/71
